name: Terraform

on:
  workflow_run:
    workflows: ["Script"]
    types:
      - completed
    status: success

jobs:
  setup:
    name: Setup
    runs-on: [self-hosted, git-workflow]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check and Create S3 and DynamoDB Resources
        run: |
          sudo chmod +x ./aws-prerequisite-resources.sh
          ./aws-prerequisite-resources.sh

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_APPLICATION_URL: $(terraform output -raw application_url)
    
      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-actions'
          message: "Application is available at: ${{ env.TF_VAR_APPLICATION_URL }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
